name: Import Events

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pakete installieren
        run: npm install

      - name: Importer starten
        run: node importer.js

      - name: Änderungen committen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add events.js

          if git diff --cached --quiet; then
            echo "Keine Änderungen"
          else
            git commit -m "Automatischer Event Import"
            git push
          fi